In [3]:
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('BlackFriday.csv')

In [25]:
data

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
...,...,...,...,...,...,...,...,...,...,...,...,...
537572,1004737,P00193542,M,36-45,16,C,1,0,1,2.0,NaN,11664
537573,1004737,P00111142,M,36-45,16,C,1,0,1,15.0,16.0,19196
537574,1004737,P00345942,M,36-45,16,C,1,0,8,15.0,NaN,8043
537575,1004737,P00285842,M,36-45,16,C,1,0,5,NaN,NaN,7172
537576,1004737,P00118242,M,36-45,16,C,1,0,5,8.0,NaN,6875

In [82]:
data.shape

(537577, 12)

In [83]:
data.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537577 entries, 0 to 537576
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     537577 non-null  int64
 1   Product_ID                  537577 non-null  object
 2   Gender                      537577 non-null  object
 3   Age                         537577 non-null  object
 4   Occupation                  537577 non-null  int64
 5   City_Category               537577 non-null  object
 6   Stay_In_Current_City_Years  537577 non-null  object
 7   Marital_Status              537577 non-null  int64
 8   Product_Category_1          537577 non-null  int64
 9   Product_Category_2          370591 non-null  float64
 10  Product_Category_3          164278 non-null  float64
 11  Purchase                    537577 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 163.0 MB

### Задачи

**1.** Сколько всего строк в датасете и сколько уникальных покупателей (`User_ID`)?

In [84]:
# Ваш код здесь
print(data.shape[0], len(set(data["User_ID"])))

537577 5891

In [85]:
# ответ: 537577, 5891

**2.** Сколько всего возрастных категорий? Какая возрастная категория встречается чаще всего и сколько?

In [86]:
# Ваш код здесь
print(len(set(data["Age"])), data["Age"].value_counts().idxmax(), data["Age"].value_counts().max())

7 26-35 214690

In [87]:
# ответ: 7, 26-35, 214690

**3.** Сколько строк с мужчинами из категории города A? (речь не об уникальных ID мужчин, а о количестве строк)

In [88]:
data[(data["Gender"] == "M") & (data["City_Category"] == "A")].shape[0]

109831

In [89]:
# ответ: 109831

**4.** Сколько женщин от 46 до 50, потративших (столбец `Purchase`) больше 20000 (условных единиц, в данном случае)?   (речь не об уникальных ID, а о количестве строк)

In [90]:
# Ваш код здесь
data[(data["Gender"] == "F") & (data["Age"] == "46-50") & (data["Purchase"] > 20000)].shape[0]

270

In [91]:
# ответ: 270

**5.** Какой средний `Purchase` у мужчин и у женщин (округлите до двух знаков после запятой)?

In [92]:
# Ваш код здесь
print(data[(data["Gender"] == "F")].Purchase.sum()/data[(data["Gender"] == "F")].shape[0], data[(data["Gender"] == "M")].Purchase.sum()/data[(data["Gender"] == "M")].shape[0])

8809.761348593387 9504.771712960679

In [93]:
# ответ: женщины: 8809.76, мужчины: 9504.77

**6.** Сколько `NaN`-ов в столбце `Product_Category_3`?

In [94]:
# Ваш код здесь
print(data["Product_Category_3"].isna().sum())

373299

In [95]:
# ответ: 373299

**7.** В каком типе города (`City_Category`) самый высокий средний чек (`Purchase`) и сколько (округлите до двух знаков после запятой)?

In [96]:
# Ваш код здесь
print(data.groupby("City_Category")["Purchase"].mean().idxmax(), data.groupby("City_Category")["Purchase"].mean().max())

C 9844.44185501604

In [97]:
# ответ: С, 9844.44

**8.** Сколько уникальных товаров (`Product_ID`) купили женщины 18–25 лет?

In [98]:
# Ваш код здесь
data[(data["Gender"] == "F") & (data["Age"] == "18-25")]["Product_ID"].nunique()

2600

In [99]:
# ответ: 2600

**9.** Какая категория товара первого уровня (`Product_Category_1`) принесла наибольшую суммарную выручку (`Purchase`)?

In [100]:
# Ваш код здесь
data.groupby("Product_Category_1")["Purchase"].sum().max()

np.int64(1882666325)

In [101]:
# ответ: 1882666325

**10.** У какой возрастной группы самый высокий средний чек (`Purchase`) и сколько (округлите до двух знаков после запятой)?

In [102]:
# Ваш код здесь
data.groupby("Age")["Purchase"].mean().idxmax(), data.groupby("Age")["Purchase"].mean().max()

('51-55', np.float64(9620.616619703333))

In [103]:
# ответ: 51-55, 9620.62

**11.** Какую долю всех строк составляют покупки из города `C`?

In [104]:
# Ваш код здесь
(data["City_Category"] == "C").mean()

np.float64(0.30962262150352415)

In [105]:
# ответ: 0.3096

**12.** У кого медианная покупка выше: у состоящих в браке или не состоящих? Сколько?

In [106]:
# Ваш код здесь
data.groupby("Marital_Status")["Purchase"].median()

Marital_Status
0    8059.0
1    8066.0
Name: Purchase, dtype: float64

In [107]:
# ответ: у состоящих в браке (1)

**13.** Какой пользователь (`User_ID`) потратил больше всего суммарно и сколько?

In [108]:
# Ваш код здесь
print(data.groupby("User_ID")["Purchase"].sum().idxmax(),  data.groupby("User_ID")["Purchase"].sum().max())

1004277 10536783

In [109]:
# ответ: User_ID: 1004277, cумма 10536783

**14.** Какую долю (вещественное число от 0 до 1, округлить до 4-го знака) от всех покупателей составляют ВМЕСТЕ мужчины от 26 до 35 лет и женщины старше 36 лет (то есть нужно учесть несколько возрастных категорий)? (речь не об уникальных ID, а о количестве таких строк)

In [110]:
# Ваш код здесь
(((data["Gender"] == "M") & (data["Age"] == "26-35")) | ((data["Gender"] == "F") & (data["Age"].isin(["36-45", "46-50", "51-55", "55+"])))).mean()

np.float64(0.4077201963625676)

In [111]:
# ответ: 0.4077

**15.** Найти топ-5 пользователей по суммарным тратам.

In [112]:
# Ваш код здесь
data.groupby("User_ID")["Purchase"].sum().sort_values(ascending=False).head(5)

User_ID
1004277    10536783
1001680     8699232
1002909     7577505
1001941     6817493
1000424     6573609
Name: Purchase, dtype: int64

In [113]:
# ответ:

# User_ID    Purchase sum
# 1004277    10536783
# 1001680     8699232
# 1002909     7577505
# 1001941     6817493
# 1000424     6573609

**16.** Для каждой возрастной группы посчитать долю мужчин и женщин в процентах (округлите до двух знаков после запятой).

In [114]:
# Ваш код здесь
data.groupby(["Age", "Gender"]).size().unstack().apply(lambda x: x / x.sum() * 100, axis=1)

Gender          F          M
Age
0-17    33.677840  66.322160
18-25   24.639982  75.360018
26-35   22.985700  77.014300
36-45   24.576973  75.423027
46-50   28.873018  71.126982
51-55   25.610080  74.389920
55+     23.580347  76.419653

In [115]:
# ответ:

# Gender	F	    M
# Age		
# 0-17	  33.68	  66.32
# 18-25	  24.64	  75.36
# 26-35	  22.99	  77.01
# 36-45	  24.58	  75.42
# 46-50	  28.87	  71.13
# 51-55	  25.61	  74.39
# 55+	  23.58	  76.42

**17.** Найти товар (`Product_ID`), который чаще всего покупали. Найти сколько всего покупали этот товар.

In [116]:
# Ваш код здесь
data["Product_ID"].value_counts().idxmax(), data["Product_ID"].value_counts().max()

('P00265242', np.int64(1858))

In [117]:
# ответ: Product_ID - P00265242, количество - 1858

**18.** Посчитать средний чек по комбинации `Gender + City_Category` (округлите до двух знаков после запятой).

In [118]:
# Ваш код здесь
data.groupby(["Gender", "City_Category"])["Purchase"].mean().round(2)

Gender  City_Category
F       A                 8630.77
        B                 8590.52
        C                 9264.96
M       A                 9061.72
        B                 9400.75
        C                10033.20
Name: Purchase, dtype: float64

In [119]:
# ответ:

# Gender  City_Category
# F       A                 8630.77
#         B                 8590.52
#         C                 9264.96
# M       A                 9061.72
#         B                 9400.75
#         C                10033.20

**19.** Найти категорию `Product_Category_1`, у которой больше всего пропусков в `Product_Category_2` и найти количество этих пропусков.

In [120]:
# Ваш код здесь
data[data["Product_Category_2"].isna()].groupby("Product_Category_1").size().idxmax(), data[data["Product_Category_2"].isna()].groupby("Product_Category_1").size().max()

(np.int64(5), np.int64(62788))

In [121]:
# ответ: 5, 62788

**20.** Для каждого города найти самую популярную возрастную группу и их количества.

In [122]:
# Ваш код здесь

In [123]:
# ответ:

# City_Category   Age    count
# A              26-35   72048
# B              26-35   89767
# C              26-35   52875